## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
sudo: required
before_install:
  - sudo ln -sf /usr/bin/gcc-7 /usr/bin/gcc
  - sudo ln -sf /usr/bin/g++-7 /usr/bin/g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Polymake")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Polymake")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
