## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
matrix:
 allow_failures:
 - julia: nightly
notifications:
  email: false
sudo: required
codecov: true
env:
  global:
    - OMP_NUM_THREADS=1
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -sf /usr/bin/gcc-7 /usr/bin/gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -sf /usr/bin/g++-7 /usr/bin/g++; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
