title = "metadata for oscar CI run"

[env]
os = [ "ubuntu-latest", "macos-latest" ]
julia-version = [ "~1.6.0-0", "~1.10.0-0"]
# branches = [ "release", "<matching>" ]

[pkgs]
  [pkgs.Oscar]
  test = true

  [pkgs.Polymake]
  branches = []
  test = true

[include]
  [include.nightly]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "nightly"
  os = "ubuntu-latest"

  [include.julia_1_10]
  Oscar = "<matching>"
  Polymake = ""
  julia-version = "~1.10.0-0"
  os = "ubuntu-latest"
