name: Run tests

on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.3', '1.4', 'nightly']
        os: [ubuntu-latest, macOS-latest]
        # empty entry for defaults
        xcode: [ '' ]
        cxxwrap: [ '' ]
        exclude:
        # only julia 1.4 on macOS
          - os: macos-latest
            julia-version: 'nightly'
          - os: macos-latest
            julia-version: '1.3'
        # add a few extra tests
        include:
          - xcode: '11.4'
            os: macos-latest
            julia-version: 1.4
          - xcode: '11.4'
            cxxwrap: '0.9'
            os: macos-latest
            julia-version: 1.4
          - cxxwrap: '0.9'
            os: macos-latest
            julia-version: 1.3
          - cxxwrap: '0.9'
            os: ubuntu-latest
            julia-version: 1.4

      fail-fast: false

    steps:
      - uses: actions/checkout@v2.1.0
      - name: "Set up docker for polyDB testing"
        if: matrix.os == ubuntu-latest
        run: docker run --network=something -d --rm=true --network-alias=db-test-server -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=admin mongo:4.2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Pin CxxWrap"
        if: matrix.cxxwrap != ''
        run: julia --project -e 'using Pkg; pkg"add CxxWrap@${{ matrix.cxxwrap }}"; pkg"pin CxxWrap";'
      - name: "set xcode"
        if: matrix.xcode != ''
        run: echo "::set-env name=DEVELOPER_DIR::/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
      - uses: julia-actions/julia-buildpkg@latest
      - name: "Fill polyDB container"
        if: matrix.os == ubuntu-latest
        run: mongorestore --host db-test-server -u admin -p admin --port 27017 .github/polydb_dump
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
