name: Run tests

on:
   push:
     branches:
       - master
       - testing/**
   pull_request:
     branches:
       - master

jobs:
  # github services (for mongodb service) only works on linux
  test-with-mongodb:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version:
          - '1.4'
          - '1.5'
          - '~1.6.0-0'
          - 'nightly'
        os: ['ubuntu-latest']
      fail-fast: false
    # Service containers to run
    services:
      # Label used to access the service container
      mongodb:
        # Docker Hub image
        image: mongo:4.2
        # Provide the login data
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
          # Maps tcp port 27017 on service container to the host
          - 27017:27017
    env:
        POLYDB_TEST_URI: "mongodb://admin:admin@localhost:27017/?authSource=admin"
    steps:
      - uses: actions/checkout@v2.1.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Fill polyDB container"
        run: mongorestore --host localhost -u admin -p admin --port 27017 .github/polydb_dump
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version:
          - '1.4'
          - '1.5'
          - '~1.6.0-0'
          - 'nightly'
        os: ['ubuntu-latest', 'macOS-latest', 'macos-11.0']
        # empty entry for defaults
        xcode: [ '' ]
        cxxwrap: [ '' ]
        exclude:
        # remove some macOS tests to keep the total number small
          - os: macos-11.0
            julia-version: '1.4'
          - os: macos-11.0
            julia-version: '1.5'
        # add a few extra tests: xcode 11.4, julia 1.3 with cxxwrap 0.11.0, legacy cxxwrap, several ubuntu lts versions
        include:
          - xcode: '11.4'
            os: macos-latest
            julia-version: 1.5
          - cxxwrap: '0.11.0'
            os: ubuntu-latest
            julia-version: 1.3
          - cxxwrap: '0.11.0'
            os: macos-latest
            julia-version: 1.3
          - cxxwrap: '0.10'
            os: ubuntu-latest
            julia-version: 1.5
          - os: ubuntu-20.04
            julia-version: 1.5
          - os: ubuntu-18.04
            julia-version: 1.5
          - os: ubuntu-16.04
            julia-version: 1.5

      fail-fast: false

    steps:
      - uses: actions/checkout@v2.1.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "pin CxxWrap"
        if: matrix.cxxwrap != ''
        run: julia --project -e 'using Pkg; pkg"add CxxWrap@${{ matrix.cxxwrap }}"; pkg"pin CxxWrap";'
      - name: "set xcode"
        if: matrix.xcode != ''
        run: echo "DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" >> $GITHUB_ENV
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
